modLoader="javafml" 
loaderVersion="[31,)"
logoFile="logo.png"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Core/issues"

[[mods]]
    modId="project_essentials_core"
    version="1.15.2-1.1.0"
    displayName="Project Essentials Core"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Core/MC-1.15.2/update.json"
    displayURL="https://github.com/ProjectEssentials/ProjectEssentials-Core"
    credits="Thanks JetBrains for Intellij IDEA license!"
    authors="MairwunNx (Pavel Erokhin)"
    description='''
    Project Essentials Core API - core module for Essentials;
    Just API with common code for Project Essentials developers.
    '''

[[dependencies.projectessentialscore]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentialscore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
